# Copyright 2020, LibreCores CI contributors
# SPDX-License-Identifier: MIT

name: 'LibreCores CI with FuseSoC'
description: 'FuseSoC action on LibreCores CI'
inputs:
  core:
    description: 'Core identifier'
    required: false
  target:
    description: 'Target'
    required: false
  tool:
    description: 'Tool to use'
    required: false
runs:
  using: 'composite'
  steps:
    - run: pip3 install fusesoc
      shell: bash
    - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
      shell: bash      
    - run: fusesoc library add ${{ inputs.core }} $GITHUB_WORKSPACE/$REPO
      shell: bash      
    - run: fusesoc run --target=${{ inputs.target }} --tool=${{ inputs.tool }}${{ inputs.core }}
      shell: bash      
branding:
  icon: 'cpu'
  color: 'green'
